CREATE TABLE GAME (
    name VARCHAR(94) NOT NULL,
    release_date VARCHAR(18) NOT NULL,
    score INTEGER NOT NULL,
    user_score VARCHAR(3) NOT NULL,
    players VARCHAR(21) NOT NULL,
    critics INTEGER NOT NULL,
    users INTEGER NOT NULL
);
ALTER TABLE GAME ADD CONSTRAINT pk_game_name PRIMARY KEY (name);

CREATE TABLE PLATFORM (
    platform_id INTEGER NOT NULL,
    platform_name VARCHAR(15) NOT NULL
);
ALTER TABLE PLATFORM ADD CONSTRAINT pk_platform_id PRIMARY KEY (platform_id);

CREATE TABLE IS_IN(
    game_name VARCHAR(94) NOT NULL,
    platform_id INTEGER NOT NULL
);
ALTER TABLE IS_IN ADD CONSTRAINT fk_game_name FOREIGN KEY (game_name) REFERENCES GAME (name);
ALTER TABLE IS_IN ADD CONSTRAINT fk_plat_id FOREIGN KEY (platform_id) REFERENCES PLATFORM (platform_id);
ALTER TABLE IS_IN ADD CONSTRAINT pk_ndea PRIMARY KEY (game_name, platform_id);

CREATE TABLE GENRE(
    genre_id INTEGER NOT NULL,
    genre_name VARCHAR(114) NOT NULL
);
ALTER TABLE GENRE ADD CONSTRAINT pk_genre_id PRIMARY KEY (genre_id);

CREATE TABLE HAS_GENRE(
    game_name VARCHAR(94) NOT NULL,
    genre_id INTEGER NOT NULL
);
ALTER TABLE HAS_GENRE ADD CONSTRAINT fk_genre_game_name FOREIGN KEY (game_name) REFERENCES GAME (name);
ALTER TABLE HAS_GENRE ADD CONSTRAINT fk_genre_g_id FOREIGN KEY (genre_id) REFERENCES GENRE (genre_id);
ALTER TABLE HAS_GENRE ADD CONSTRAINT pk_genre_game PRIMARY KEY (game_name, genre_id);

CREATE TABLE DEVELOPER(
    dev_id INTEGER NOT NULL,
    dev_name VARCHAR(32) NOT NULL
);
ALTER TABLE DEVELOPER ADD CONSTRAINT pk_dev_id PRIMARY KEY (dev_id);


CREATE TABLE WAS_DEV(
    game_name VARCHAR(94) NOT NULL,
    dev_id INTEGER NOT NULL
);
ALTER TABLE WAS_DEV ADD CONSTRAINT fk_was_dev_game FOREIGN KEY (game_name) REFERENCES GAME (name);
ALTER TABLE WAS_DEV ADD CONSTRAINT fk_was_dev_id FOREIGN KEY (dev_id) REFERENCES DEVELOPER (dev_id);
ALTER TABLE WAS_DEV ADD CONSTRAINT pk_was_dev PRIMARY KEY (game_name, dev_id);
